package indexer

import (
	"strings"
	"testing"
)

func TestSelect_decisionTable(t *testing.T) {
	// The table IS the specification for what rongo indexes. Every skip reason
	// exists because that content would either cost money for nothing or
	// actively dilute results: a vendored dependency outranks the real answer
	// for any query about a common word.
	cases := []struct {
		name string
		path string
		body string
		want Decision
	}{
		{
			name: "ordinary source is included",
			path: "src/cart/AbandonedCartJob.java",
			body: "class AbandonedCartJob {\n  void run() {}\n}\n",
			want: Include,
		},
		{
			name: "node_modules is vendored",
			path: "node_modules/left-pad/index.js",
			body: "module.exports = function () {}\n",
			want: SkipVendored,
		},
		{
			name: "go vendor directory is vendored",
			path: "vendor/github.com/x/y/z.go",
			body: "package y\n",
			want: SkipVendored,
		},
		{
			name: "nested vendor directory is vendored",
			path: "services/api/node_modules/dep/a.js",
			body: "export const a = 1\n",
			want: SkipVendored,
		},
		{
			name: "build output is generated",
			path: "ui/dist/assets/index-abc123.js",
			body: "console.log(1)\n",
			want: SkipGenerated,
		},
		{
			name: "minified file is generated",
			path: "static/app.min.js",
			body: "!function(){}();\n",
			want: SkipGenerated,
		},
		{
			name: "protoc marker in content is generated",
			path: "api/v1/service.pb.go",
			body: "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage v1\n",
			want: SkipGenerated,
		},
		{
			name: "lock file is generated",
			path: "package-lock.json",
			body: `{"lockfileVersion": 3}`,
			want: SkipGenerated,
		},
		{
			name: "go.sum is generated",
			path: "go.sum",
			body: "example.com/x v1.0.0 h1:abc=\n",
			want: SkipGenerated,
		},
		{
			name: "NUL byte means binary",
			path: "assets/logo.dat",
			body: "PNG\x00\x01\x02binary",
			want: SkipBinary,
		},
		{
			name: "oversized file is skipped whole",
			path: "src/Huge.java",
			body: strings.Repeat("x", 3<<20),
			want: SkipTooLarge,
		},
		{
			name: "aws access key id is a secret",
			path: "config/deploy.sh",
			body: "export KEY=AKIAIOSFODNN7EXAMPLE\n",
			want: SkipSecret,
		},
		{
			name: "private key block is a secret",
			path: "certs/id_rsa",
			body: "-----BEGIN RSA PRIVATE KEY-----\nMIIEow...\n",
			want: SkipSecret,
		},
		{
			name: "github token is a secret",
			path: "scripts/publish.sh",
			body: "GH_TOKEN=ghp_A1b2C3d4E5f6G7h8I9j0K1l2M3n4O5p6Q7r8\n",
			want: SkipSecret,
		},
	}

	s := NewSelector(DefaultSelectOptions())
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got, reason := s.Select(tc.path, []byte(tc.body))

			if got != tc.want {
				t.Errorf("Select(%q) = %v (%s), want %v", tc.path, got, reason, tc.want)
			}
			if got != Include && reason == "" {
				t.Error("a skipped file must carry a reason, so the answer layer can say why it was not indexed")
			}
		})
	}
}

func TestSelect_excludedPaths(t *testing.T) {
	// The patterns are anchored at the repository root and matched segment by
	// segment, so a directory name is never mistaken for a prefix of another
	// and a nested copy is only excluded when the pattern says "**".
	cases := []struct {
		name    string
		exclude []string
		path    string
		want    Decision
	}{
		{
			name:    "the default keeps design documents out",
			exclude: []string{"docs/plans/**"},
			path:    "docs/plans/rongo-spec.html",
			want:    SkipExcluded,
		},
		{
			name:    "deeper files under the directory are excluded too",
			exclude: []string{"docs/plans/**"},
			path:    "docs/plans/2026/phase-3.md",
			want:    SkipExcluded,
		},
		{
			name:    "a sibling whose name merely starts the same is kept",
			exclude: []string{"docs/plans/**"},
			path:    "docs/plans-notes.md",
			want:    Include,
		},
		{
			name:    "the pattern is anchored at the root",
			exclude: []string{"docs/plans/**"},
			path:    "services/x/docs/plans/a.md",
			want:    Include,
		},
		{
			name:    "a leading ** matches at any depth",
			exclude: []string{"**/docs/plans/**"},
			path:    "services/x/docs/plans/a.md",
			want:    SkipExcluded,
		},
		{
			name:    "a leading ** also matches at the root",
			exclude: []string{"**/docs/plans/**"},
			path:    "docs/plans/a.md",
			want:    SkipExcluded,
		},
		{
			name:    "a file glob in the last segment",
			exclude: []string{"docs/**/*.html"},
			path:    "docs/plans/rongo-ui-mock.html",
			want:    SkipExcluded,
		},
		{
			name:    "the file glob does not catch other extensions",
			exclude: []string{"docs/**/*.html"},
			path:    "docs/plans/phase-2.md",
			want:    Include,
		},
		{
			name:    "a bare directory name without ** is the directory itself, not its files",
			exclude: []string{"docs/plans"},
			path:    "docs/plans/a.md",
			want:    Include,
		},
		{
			name:    "no patterns exclude nothing",
			exclude: nil,
			path:    "docs/plans/a.md",
			want:    Include,
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			s := NewSelector(SelectOptions{Exclude: tc.exclude})

			got, reason := s.Select(tc.path, []byte("# heading\n\nbody\n"))

			if got != tc.want {
				t.Errorf("Select(%q) with %v = %v (%s), want %v", tc.path, tc.exclude, got, reason, tc.want)
			}
		})
	}
}

func TestSelect_secretDetectionBeatsExcluded(t *testing.T) {
	// Given: an excluded document that also holds a credential. Exclusion is
	// about relevance; the secret verdict is about a credential never leaving
	// the network, and it also decides what gets reported.
	s := NewSelector(SelectOptions{Exclude: []string{"docs/plans/**"}})

	got, reason := s.Select("docs/plans/deploy-notes.md",
		[]byte("export KEY=AKIAIOSFODNN7EXAMPLE\n"))

	if got != SkipSecret {
		t.Errorf("Select() = %v (%s), want SkipSecret — a credential outranks an exclusion", got, reason)
	}
}

func TestValidateExclude(t *testing.T) {
	// A malformed pattern must fail at startup: silently matching nothing
	// would leave the excluded content in the index while the configuration
	// looked right.
	if err := ValidateExclude([]string{"docs/plans/**", "**/*.html"}); err != nil {
		t.Errorf("ValidateExclude(valid) err = %v, want nil", err)
	}
	if err := ValidateExclude([]string{"docs/[plans/**"}); err == nil {
		t.Error("ValidateExclude(unclosed bracket) err = nil, want an error")
	}
	if err := ValidateExclude([]string{""}); err == nil {
		t.Error("ValidateExclude(empty pattern) err = nil, want an error")
	}
	// Paths are cleaned before matching, so these could never match anything
	// and would fail silently instead of loudly.
	for _, pat := range []string{"docs/plans/", "/docs/plans/**", "./docs/plans/**", "docs//plans/**", "../docs/**", "docs/**.html"} {
		if err := ValidateExclude([]string{pat}); err == nil {
			t.Errorf("ValidateExclude(%q) err = nil, want an error for a pattern that can never match", pat)
		}
	}
}

func TestSelect_secretDetectionBeatsEveryOtherSkip(t *testing.T) {
	// Given: a vendored file that also contains a credential. The vendored
	// verdict alone would be harmless, but the ORDER matters for a different
	// reason: whichever check wins decides what gets reported, and a credential
	// found anywhere in the corpus is worth surfacing.
	s := NewSelector(DefaultSelectOptions())

	got, reason := s.Select("node_modules/dep/config.js",
		[]byte("const k = 'AKIAIOSFODNN7EXAMPLE'\n"))

	if got != SkipSecret {
		t.Errorf("Select() = %v (%s), want SkipSecret — a credential outranks a vendored verdict", got, reason)
	}
}

func TestSelect_secretDetectionRunsBeforeEmbedding(t *testing.T) {
	// Given: this is the property the whole check exists for. Code leaves the
	// network when it is embedded; an accidentally committed credential must
	// not leave with it. The selector is the only thing standing between the
	// two, so it must reject on CONTENT, not merely on a suspicious filename.
	s := NewSelector(DefaultSelectOptions())

	got, _ := s.Select("src/perfectly/ordinary/Service.java",
		[]byte("class Service {\n  String t = \"ghp_A1b2C3d4E5f6G7h8I9j0K1l2M3n4O5p6Q7r8\";\n}\n"))

	if got != SkipSecret {
		t.Errorf("Select() = %v, want SkipSecret for a credential in an ordinary-looking source file", got)
	}
}

func TestLanguageOf(t *testing.T) {
	cases := map[string]string{
		"src/A.java":        "java",
		"main.go":           "go",
		"ui/src/App.tsx":    "tsx",
		"ui/src/index.ts":   "ts",
		"scripts/build.sh":  "sh",
		"README.md":         "md",
		"config/app.yaml":   "yaml",
		"Makefile":          "",
		"src/unknown.xyzzy": "",
	}
	for path, want := range cases {
		if got := LanguageOf(path); got != want {
			t.Errorf("LanguageOf(%q) = %q, want %q", path, got, want)
		}
	}
}
