package indexer

import (
	"strings"
	"testing"
)

func TestSelect_decisionTable(t *testing.T) {
	// The table IS the specification for what rongo indexes. Every skip reason
	// exists because that content would either cost money for nothing or
	// actively dilute results: a vendored dependency outranks the real answer
	// for any query about a common word.
	cases := []struct {
		name string
		path string
		body string
		want Decision
	}{
		{
			name: "ordinary source is included",
			path: "src/cart/AbandonedCartJob.java",
			body: "class AbandonedCartJob {\n  void run() {}\n}\n",
			want: Include,
		},
		{
			name: "node_modules is vendored",
			path: "node_modules/left-pad/index.js",
			body: "module.exports = function () {}\n",
			want: SkipVendored,
		},
		{
			name: "go vendor directory is vendored",
			path: "vendor/github.com/x/y/z.go",
			body: "package y\n",
			want: SkipVendored,
		},
		{
			name: "nested vendor directory is vendored",
			path: "services/api/node_modules/dep/a.js",
			body: "export const a = 1\n",
			want: SkipVendored,
		},
		{
			name: "build output is generated",
			path: "ui/dist/assets/index-abc123.js",
			body: "console.log(1)\n",
			want: SkipGenerated,
		},
		{
			name: "minified file is generated",
			path: "static/app.min.js",
			body: "!function(){}();\n",
			want: SkipGenerated,
		},
		{
			name: "protoc marker in content is generated",
			path: "api/v1/service.pb.go",
			body: "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage v1\n",
			want: SkipGenerated,
		},
		{
			name: "lock file is generated",
			path: "package-lock.json",
			body: `{"lockfileVersion": 3}`,
			want: SkipGenerated,
		},
		{
			name: "go.sum is generated",
			path: "go.sum",
			body: "example.com/x v1.0.0 h1:abc=\n",
			want: SkipGenerated,
		},
		{
			name: "NUL byte means binary",
			path: "assets/logo.dat",
			body: "PNG\x00\x01\x02binary",
			want: SkipBinary,
		},
		{
			name: "oversized file is skipped whole",
			path: "src/Huge.java",
			body: strings.Repeat("x", 3<<20),
			want: SkipTooLarge,
		},
		{
			name: "aws access key id is a secret",
			path: "config/deploy.sh",
			body: "export KEY=AKIAIOSFODNN7EXAMPLE\n",
			want: SkipSecret,
		},
		{
			name: "private key block is a secret",
			path: "certs/id_rsa",
			body: "-----BEGIN RSA PRIVATE KEY-----\nMIIEow...\n",
			want: SkipSecret,
		},
		{
			name: "github token is a secret",
			path: "scripts/publish.sh",
			body: "GH_TOKEN=ghp_A1b2C3d4E5f6G7h8I9j0K1l2M3n4O5p6Q7r8\n",
			want: SkipSecret,
		},
	}

	s := NewSelector(DefaultSelectOptions())
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got, reason := s.Select(tc.path, []byte(tc.body))

			if got != tc.want {
				t.Errorf("Select(%q) = %v (%s), want %v", tc.path, got, reason, tc.want)
			}
			if got != Include && reason == "" {
				t.Error("a skipped file must carry a reason, so the answer layer can say why it was not indexed")
			}
		})
	}
}

func TestSelect_secretDetectionBeatsEveryOtherSkip(t *testing.T) {
	// Given: a vendored file that also contains a credential. The vendored
	// verdict alone would be harmless, but the ORDER matters for a different
	// reason: whichever check wins decides what gets reported, and a credential
	// found anywhere in the corpus is worth surfacing.
	s := NewSelector(DefaultSelectOptions())

	got, reason := s.Select("node_modules/dep/config.js",
		[]byte("const k = 'AKIAIOSFODNN7EXAMPLE'\n"))

	if got != SkipSecret {
		t.Errorf("Select() = %v (%s), want SkipSecret — a credential outranks a vendored verdict", got, reason)
	}
}

func TestSelect_secretDetectionRunsBeforeEmbedding(t *testing.T) {
	// Given: this is the property the whole check exists for. Code leaves the
	// network when it is embedded; an accidentally committed credential must
	// not leave with it. The selector is the only thing standing between the
	// two, so it must reject on CONTENT, not merely on a suspicious filename.
	s := NewSelector(DefaultSelectOptions())

	got, _ := s.Select("src/perfectly/ordinary/Service.java",
		[]byte("class Service {\n  String t = \"ghp_A1b2C3d4E5f6G7h8I9j0K1l2M3n4O5p6Q7r8\";\n}\n"))

	if got != SkipSecret {
		t.Errorf("Select() = %v, want SkipSecret for a credential in an ordinary-looking source file", got)
	}
}

func TestLanguageOf(t *testing.T) {
	cases := map[string]string{
		"src/A.java":        "java",
		"main.go":           "go",
		"ui/src/App.tsx":    "tsx",
		"ui/src/index.ts":   "ts",
		"scripts/build.sh":  "sh",
		"README.md":         "md",
		"config/app.yaml":   "yaml",
		"Makefile":          "",
		"src/unknown.xyzzy": "",
	}
	for path, want := range cases {
		if got := LanguageOf(path); got != want {
			t.Errorf("LanguageOf(%q) = %q, want %q", path, got, want)
		}
	}
}
