package indexer

import (
	"strings"
	"testing"
)

func TestSelect_decisionTable(t *testing.T) {
	// The table IS the specification for what rongo indexes. Every skip reason
	// exists because that content would either cost money for nothing or
	// actively dilute results: a vendored dependency outranks the real answer
	// for any query about a common word.
	cases := []struct {
		name string
		path string
		body string
		want Decision
	}{
		{
			name: "ordinary source is included",
			path: "src/cart/AbandonedCartJob.java",
			body: "class AbandonedCartJob {\n  void run() {}\n}\n",
			want: Include,
		},
		{
			name: "node_modules is vendored",
			path: "node_modules/left-pad/index.js",
			body: "module.exports = function () {}\n",
			want: SkipVendored,
		},
		{
			name: "go vendor directory is vendored",
			path: "vendor/github.com/x/y/z.go",
			body: "package y\n",
			want: SkipVendored,
		},
		{
			name: "nested vendor directory is vendored",
			path: "services/api/node_modules/dep/a.js",
			body: "export const a = 1\n",
			want: SkipVendored,
		},
		{
			name: "build output is generated",
			path: "ui/dist/assets/index-abc123.js",
			body: "console.log(1)\n",
			want: SkipGenerated,
		},
		{
			name: "minified file is generated",
			path: "static/app.min.js",
			body: "!function(){}();\n",
			want: SkipGenerated,
		},
		{
			name: "protoc marker in content is generated",
			path: "api/v1/service.pb.go",
			body: "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage v1\n",
			want: SkipGenerated,
		},
		{
			name: "lock file is generated",
			path: "package-lock.json",
			body: `{"lockfileVersion": 3}`,
			want: SkipGenerated,
		},
		{
			name: "go.sum is generated",
			path: "go.sum",
			body: "example.com/x v1.0.0 h1:abc=\n",
			want: SkipGenerated,
		},
		{
			name: "NUL byte means binary",
			path: "assets/logo.dat",
			body: "PNG\x00\x01\x02binary",
			want: SkipBinary,
		},
		{
			name: "oversized file is skipped whole",
			path: "src/Huge.java",
			body: strings.Repeat("x", 3<<20),
			want: SkipTooLarge,
		},
		{
			name: "aws access key id is a secret",
			path: "config/deploy.sh",
			body: "export KEY=AKIAIOSFODNN7EXAMPLE\n",
			want: SkipSecret,
		},
		{
			name: "private key block is a secret",
			path: "certs/id_rsa",
			body: "-----BEGIN RSA PRIVATE KEY-----\nMIIEow...\n",
			want: SkipSecret,
		},
		{
			name: "github token is a secret",
			path: "scripts/publish.sh",
			body: "GH_TOKEN=ghp_A1b2C3d4E5f6G7h8I9j0K1l2M3n4O5p6Q7r8\n",
			want: SkipSecret,
		},
		{
			name: "a sealed secret manifest is a secret whole",
			path: "prod/intranet/masterkey.yaml",
			body: "apiVersion: bitnami.com/v1alpha1\nkind: SealedSecret\nspec:\n  encryptedData:\n    masterkey: AgBx\n",
			want: SkipSecret,
		},
		{
			name: "a plain secret manifest is a secret whole",
			path: "base/db-secret.yml",
			body: "apiVersion: v1\nkind: Secret\ndata:\n  password: aHVudGVyMg==\n",
			want: SkipSecret,
		},
		{
			name: "a properties file with encrypted values is included, redacted",
			path: "prod/application.properties",
			body: "db.url=jdbc:postgresql://db/app\ndb.password=ENC(abc)\n",
			want: Include,
		},
		{
			name: "a properties token line matching a hard shape is included once redacted",
			path: "prod/application.properties",
			body: "forge.token=ghp_A1b2C3d4E5f6G7h8I9j0K1l2M3n4O5p6Q7r8\n",
			want: Include,
		},
		// Generated by name: a translation bundle a generator wrote is skipped
		// however small, because its name says what it is.
		{
			name: "a file named generated is generated whatever its size",
			path: "libs/schadenmeldung-lib/src/lib/i18n/generated-de-CH.json",
			body: `{"cart.title": "Warenkorb"}`,
			want: SkipGenerated,
		},
		{
			name: "a translation directory is generated",
			path: "apps/shop/src/locales/en.json",
			body: `{"cart.title": "Cart"}`,
			want: SkipGenerated,
		},
		{
			name: "a jest snapshot directory is generated",
			path: "src/cart/__snapshots__/Cart.test.tsx.snap",
			body: "exports[`renders`] = `<div/>`;\n",
			want: SkipGenerated,
		},
		{
			name: "a generator suffix is generated without a marker",
			path: "api/v1/service.pb.go",
			body: "package v1\n",
			want: SkipGenerated,
		},
		{
			name: "an @generated marker is generated",
			path: "src/schema.ts",
			body: "/**\n * @generated by graphql-codegen\n */\nexport type Q = {}\n",
			want: SkipGenerated,
		},
		{
			name: "Cargo.lock is a lock file by suffix",
			path: "Cargo.lock",
			body: "[[package]]\nname = \"x\"\n",
			want: SkipGenerated,
		},
		// Data formats: rows, not code. Nothing in them answers how anything works.
		{
			name: "csv is data",
			path: "backend/data/plz.csv",
			body: "plz,ort\n8000,Zürich\n",
			want: SkipData,
		},
		{
			name: "a source map is data",
			path: "static/app.js.map",
			body: `{"version":3,"sources":["a.ts"]}`,
			want: SkipData,
		},
		{
			name: "an xliff translation file is data",
			path: "src/messages.de.xlf",
			body: "<xliff version=\"1.2\"></xliff>\n",
			want: SkipData,
		},
		// Long data files: json and xml above the data ceiling are machine
		// output or translations, never the answer.
		{
			name: "json above the data ceiling is data",
			path: "backend/data/plz_ch.json",
			body: "[" + strings.Repeat(`{"plz":8000,"ort":"Zürich"},`, 400) + "]",
			want: SkipData,
		},
		{
			name: "xml above the data ceiling is data",
			path: "resources/import/cantons.xml",
			body: "<cantons>" + strings.Repeat("<canton code=\"ZH\">Zürich</canton>\n", 300) + "</cantons>",
			want: SkipData,
		},
		{
			name: "json under the data ceiling is included",
			path: "apps/shop/tsconfig.app.json",
			body: `{"extends": "../../tsconfig.base.json"}`,
			want: Include,
		},
		{
			name: "a manifest above the data ceiling is included, structure comes from it",
			path: "services/order/pom.xml",
			body: "<project>" + strings.Repeat("<dependency><groupId>org.example</groupId><artifactId>x</artifactId></dependency>\n", 200) + "</project>",
			want: Include,
		},
		{
			name: "a manifest under a generated directory is generated",
			path: "generated/client/package.json",
			body: `{"name": "client"}`,
			want: SkipGenerated,
		},
		{
			name: "yaml is never capped by the data ceiling",
			path: "deploy/helm/values.yaml",
			body: strings.Repeat("replicaCount: 2\nimage:\n  repository: shop\n", 500),
			want: Include,
		},
	}

	s := NewSelector(DefaultSelectOptions())
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got, reason := s.Select(tc.path, []byte(tc.body))

			if got != tc.want {
				t.Errorf("Select(%q) = %v (%s), want %v", tc.path, got, reason, tc.want)
			}
			if got != Include && reason == "" {
				t.Error("a skipped file must carry a reason, so the answer layer can say why it was not indexed")
			}
		})
	}
}

func TestSelect_nameBeatsSize(t *testing.T) {
	// A generated translation bundle is reported as generated, not as data,
	// whether it is 3 KB or 300 KB: the name is the better reason.
	s := NewSelector(DefaultSelectOptions())
	small := `{"a": "b"}`
	big := "{" + strings.Repeat(`"cart.title": "Warenkorb",`, 1000) + `"x": "y"}`
	for _, body := range []string{small, big} {
		got, reason := s.Select("src/i18n/generated-de-CH.json", []byte(body))
		if got != SkipGenerated {
			t.Errorf("Select(%d bytes) = %v (%s), want %v", len(body), got, reason, SkipGenerated)
		}
	}
}

func TestSelect_dataCeilingIsConfigurable(t *testing.T) {
	// The ceiling is a knob, and the reason names it, so an operator who
	// sees "why is my openapi.json missing" learns which number to raise.
	s := NewSelector(SelectOptions{MaxDataBytes: 64})
	got, reason := s.Select("api/openapi.json", []byte(strings.Repeat(`{"a":1}`, 20)))
	if got != SkipData {
		t.Fatalf("Select() = %v, want %v", got, SkipData)
	}
	if !strings.Contains(reason, "64") || !strings.Contains(reason, "json") {
		t.Errorf("reason = %q, want the format and the ceiling in it", reason)
	}
	if got, _ := s.Select("api/openapi.json", []byte(`{"a":1}`)); got != Include {
		t.Errorf("Select(small) = %v, want include", got)
	}
}

func TestSelectByPath_matchesSelectBody(t *testing.T) {
	// The sweep runs selectByPath over rows it never reads, so for every
	// verdict that needs only the path and the size, the two must agree —
	// otherwise a boot would retire files the next full index re-embeds.
	s := NewSelector(SelectOptions{Exclude: []string{"docs/plans/**"}})
	cases := []struct {
		path string
		size int
	}{
		{"docs/plans/phase-2.md", 100},
		{"node_modules/x/index.js", 100},
		{"ui/dist/app.js", 100},
		{"src/i18n/generated-de-CH.json", 100},
		{"src/locales/de.json", 100},
		{"api/v1/service.pb.go", 100},
		{"data/plz.csv", 100},
		{"data/plz.json", 100000},
		{"pom.xml", 100000},
		{"src/Main.java", 100},
		{"deploy/values.yaml", 100000},
	}
	for _, tc := range cases {
		body := []byte(strings.Repeat("x", tc.size))
		wantD, wantR, _ := s.SelectBody(tc.path, body)
		gotD, gotR := s.selectByPath(tc.path, tc.size)
		if gotD != wantD || gotR != wantR {
			t.Errorf("selectByPath(%q) = %v (%s), SelectBody = %v (%s)", tc.path, gotD, gotR, wantD, wantR)
		}
	}
}

func TestSelectBody_returnsTheRedactedBody(t *testing.T) {
	s := NewSelector(DefaultSelectOptions())
	got, _, body := s.SelectBody("prod/application.properties", []byte("db.password=ENC(abc)\nx=1\n"))
	if got != Include {
		t.Fatalf("decision = %v, want include", got)
	}
	if string(body) != "db.password=<redacted>\nx=1\n" {
		t.Fatalf("body = %q", body)
	}
	_, _, same := s.SelectBody("Main.java", []byte("class Main {}\n"))
	if string(same) != "class Main {}\n" {
		t.Fatalf("a source file came back changed: %q", same)
	}
}

func TestSelect_excludedPaths(t *testing.T) {
	// The patterns are anchored at the repository root and matched segment by
	// segment, so a directory name is never mistaken for a prefix of another
	// and a nested copy is only excluded when the pattern says "**".
	cases := []struct {
		name    string
		exclude []string
		path    string
		want    Decision
	}{
		{
			name:    "the default keeps design documents out",
			exclude: []string{"docs/plans/**"},
			path:    "docs/plans/rongo-spec.html",
			want:    SkipExcluded,
		},
		{
			name:    "deeper files under the directory are excluded too",
			exclude: []string{"docs/plans/**"},
			path:    "docs/plans/2026/phase-3.md",
			want:    SkipExcluded,
		},
		{
			name:    "a sibling whose name merely starts the same is kept",
			exclude: []string{"docs/plans/**"},
			path:    "docs/plans-notes.md",
			want:    Include,
		},
		{
			name:    "the pattern is anchored at the root",
			exclude: []string{"docs/plans/**"},
			path:    "services/x/docs/plans/a.md",
			want:    Include,
		},
		{
			name:    "a leading ** matches at any depth",
			exclude: []string{"**/docs/plans/**"},
			path:    "services/x/docs/plans/a.md",
			want:    SkipExcluded,
		},
		{
			name:    "a leading ** also matches at the root",
			exclude: []string{"**/docs/plans/**"},
			path:    "docs/plans/a.md",
			want:    SkipExcluded,
		},
		{
			name:    "a file glob in the last segment",
			exclude: []string{"docs/**/*.html"},
			path:    "docs/plans/rongo-ui-mock.html",
			want:    SkipExcluded,
		},
		{
			name:    "the file glob does not catch other extensions",
			exclude: []string{"docs/**/*.html"},
			path:    "docs/plans/phase-2.md",
			want:    Include,
		},
		{
			name:    "a bare directory name without ** is the directory itself, not its files",
			exclude: []string{"docs/plans"},
			path:    "docs/plans/a.md",
			want:    Include,
		},
		{
			name:    "no patterns exclude nothing",
			exclude: nil,
			path:    "docs/plans/a.md",
			want:    Include,
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			s := NewSelector(SelectOptions{Exclude: tc.exclude})

			got, reason := s.Select(tc.path, []byte("# heading\n\nbody\n"))

			if got != tc.want {
				t.Errorf("Select(%q) with %v = %v (%s), want %v", tc.path, tc.exclude, got, reason, tc.want)
			}
		})
	}
}

func TestSelect_secretDetectionBeatsExcluded(t *testing.T) {
	// Given: an excluded document that also holds a credential. Exclusion is
	// about relevance; the secret verdict is about a credential never leaving
	// the network, and it also decides what gets reported.
	s := NewSelector(SelectOptions{Exclude: []string{"docs/plans/**"}})

	got, reason := s.Select("docs/plans/deploy-notes.md",
		[]byte("export KEY=AKIAIOSFODNN7EXAMPLE\n"))

	if got != SkipSecret {
		t.Errorf("Select() = %v (%s), want SkipSecret — a credential outranks an exclusion", got, reason)
	}
}

func TestValidateExclude(t *testing.T) {
	// A malformed pattern must fail at startup: silently matching nothing
	// would leave the excluded content in the index while the configuration
	// looked right.
	if err := ValidateExclude([]string{"docs/plans/**", "**/*.html"}); err != nil {
		t.Errorf("ValidateExclude(valid) err = %v, want nil", err)
	}
	if err := ValidateExclude([]string{"docs/[plans/**"}); err == nil {
		t.Error("ValidateExclude(unclosed bracket) err = nil, want an error")
	}
	if err := ValidateExclude([]string{""}); err == nil {
		t.Error("ValidateExclude(empty pattern) err = nil, want an error")
	}
	// Paths are cleaned before matching, so these could never match anything
	// and would fail silently instead of loudly.
	for _, pat := range []string{"docs/plans/", "/docs/plans/**", "./docs/plans/**", "docs//plans/**", "../docs/**", "docs/**.html"} {
		if err := ValidateExclude([]string{pat}); err == nil {
			t.Errorf("ValidateExclude(%q) err = nil, want an error for a pattern that can never match", pat)
		}
	}
}

func TestSelect_secretDetectionBeatsEveryOtherSkip(t *testing.T) {
	// Given: a vendored file that also contains a credential. The vendored
	// verdict alone would be harmless, but the ORDER matters for a different
	// reason: whichever check wins decides what gets reported, and a credential
	// found anywhere in the corpus is worth surfacing.
	s := NewSelector(DefaultSelectOptions())

	got, reason := s.Select("node_modules/dep/config.js",
		[]byte("const k = 'AKIAIOSFODNN7EXAMPLE'\n"))

	if got != SkipSecret {
		t.Errorf("Select() = %v (%s), want SkipSecret — a credential outranks a vendored verdict", got, reason)
	}
}

func TestSelect_secretDetectionRunsBeforeEmbedding(t *testing.T) {
	// Given: this is the property the whole check exists for. Code leaves the
	// network when it is embedded; an accidentally committed credential must
	// not leave with it. The selector is the only thing standing between the
	// two, so it must reject on CONTENT, not merely on a suspicious filename.
	s := NewSelector(DefaultSelectOptions())

	got, _ := s.Select("src/perfectly/ordinary/Service.java",
		[]byte("class Service {\n  String t = \"ghp_A1b2C3d4E5f6G7h8I9j0K1l2M3n4O5p6Q7r8\";\n}\n"))

	if got != SkipSecret {
		t.Errorf("Select() = %v, want SkipSecret for a credential in an ordinary-looking source file", got)
	}
}

func TestLanguageOf(t *testing.T) {
	cases := map[string]string{
		"src/A.java":        "java",
		"main.go":           "go",
		"ui/src/App.tsx":    "tsx",
		"ui/src/index.ts":   "ts",
		"scripts/build.sh":  "sh",
		"README.md":         "md",
		"config/app.yaml":   "yaml",
		"Makefile":          "",
		"src/unknown.xyzzy": "",
	}
	for path, want := range cases {
		if got := LanguageOf(path); got != want {
			t.Errorf("LanguageOf(%q) = %q, want %q", path, got, want)
		}
	}
}
